Create IsItUp helm chart for public use #94
fuchicorp/helm_charts pull request #95
Opened 2022-01-13 18:15 UTC by alimer08

Hello Team!

I have created IsItUp Helm Chart and it has been tested by me and it is working.
Please review, test, and approve it.

Thank you!
Ali M

2022-01-13 18:17 UTC, osmdilya approved these changes

2022-01-14 17:34 UTC, omiradil approved these changes

2022-01-17 15:54 UTC, fsadykov requested changes
This PR definitely needs to work on!!

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/JenkinsBuilder.groovy
> +common.runPipeline()
Why we have groovy files here?

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/docker/Dockerfile
> +## Create kube folder insied root Copy KuberConfig to the docker images
Why we have docker files and the path of the files are incorrect

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/docker/README.md
> +Docker compose has environment variables configured see below all env
Why we need the documentation about docker compose in helm chart strucure?

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/docker/docker-compose.yaml
> +
We don't need docker compose files

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/docker/isitup/app.py
> +    return jsonify({"message": "Successful"})
We don't need the application in helm chart structure

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/terraform/charts/isitup/values.yaml
> +        name: ${isitup_credentials}
The helm chart still using terraform variables

2022-01-17 15:54 UTC, fsadykov commented on stable/isitup/deployment/terraform/output.tf
> +  }
Delete the terraform files

2022-01-27 00:24 UTC, fsadykov requested changes
Needs to work on

2022-01-27 00:24 UTC, fsadykov commented on stable/isitup-test/.helmignore
> +.bzr/
Remove isitup-test we don't need this at all

2022-01-27 00:24 UTC, fsadykov commented on stable/isitup/templates/proxy-deploy.yaml
> +apiVersion: apps/v1
Add the if statement for proxy to be enabled or disabled

2022-01-27 00:24 UTC, fsadykov commented on stable/isitup/templates/proxy-ingress.yaml
> +apiVersion: networking.k8s.io/v1beta1
If statement here as well

2022-02-03 02:50 UTC, bermet-s approved these changes

2022-02-03 02:51 UTC, rahymov approved these changes

2022-02-03 02:51 UTC, fuchicorp-manage approved these changes

2022-02-03 02:51 UTC, fuchicorp-manage approved these changes

2022-02-03 02:52 UTC, fsadykov approved these changes

2022-02-03 02:52 UTC, merged